# config.yaml صالح لـ code-server 4.x+
bind-addr: 0.0.0.0:${PORT:-8080}
auth: password
password: ${PASSWORD:-default_password}

# إعدادات الشبكة
proxy-protocol: false
socket: /home/developer/.config/code-server/socket.sock

# إعدادات التطبيق
disable-telemetry: true
disable-update-check: true
disable-workspace-trust: true

# إعدادات المحرر
editor:
  font-family: "Fira Code, Droid Sans Mono, monospace"
  font-size: 14
  tab-size: 2
  auto-save: "on"

# إعدادات التمديدات (يتم تثبيتها عبر Dockerfile)
extensions:
  - ms-python.python
  - eamodio.gitlens
