bind-addr: 0.0.0.0:10000
auth: password
password: SecurePass@123
cert: false
disable-telemetry: true
disable-update-check: true
user-data-dir: /home/developer/.local/share/code-server
extensions-dir: /home/developer/.local/share/code-server/extensions
