version: '3.8'

services:
  code-server:
    build:
      context: .
      args:
        USER_UID: 1001
        USER_GID: 1001
    image: my-code-server
    restart: unless-stopped
    environment:
      - CODE_SERVER_PASSWORD=SecurePass@123
      - PASSWORD=SecurePass@123
      - USER=developer
      - PORT=8080
    volumes:
      - ./workspace:/home/developer/workspace
      - ./config:/home/developer/.config/code-server
      - ./extensions:/home/developer/.local/share/code-server/extensions
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1GB
