version: '3.8'

services:
  code-server:
    build: .
    container_name: code-server
    restart: unless-stopped
    environment:
      - CODE_SERVER_PASSWORD=your_local_password
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - ./workspace:/home/coder/workspace
      - ./config:/home/coder/.config/code-server
      - ./extensions:/home/coder/.local/share/code-server/extensions
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3