services:
  - type: web
    name: code-server
    env: docker
    plan: standard
    region: frankfurt
    dockerfilePath: Dockerfile
    healthCheckPath: /
    envVars:
      - key: CODE_SERVER_PASSWORD
        value: mysecret123
      - key: PUID
        value: 1000
      - key: PGID
        value: 1000
    autoDeploy: true
    resources:
      cpu: 2
      memoryGB: 4
      diskGB: 10
