services:
  - type: web
    name: code-server-render
    env: docker
    plan: standard
    region: frankfurt
    dockerfilePath: Dockerfile
    healthCheckPath: /
    envVars:
      - key: CODE_SECURITY_HEADERS
        value: "true"
      - key: CODE_SERVER_PASSWORD
        value: "SecurePass@123"
      - key: PASSWORD
        value: "SecurePass@123"
      - key: USER
        value: "developer"
      - key: PORT
        value: "8080"
    autoDeploy: true
