services:
  - type: web
    name: code-server
    env: docker
    plan: standard
    region: frankfurt # اختر المنطقة الأقرب إليك
    dockerfilePath: Dockerfile
    healthCheckPath: /
    envVars:
      - key: PASSWORD
        value: "SecurePass@123"
      - key: SUDO_PASSWORD
        value: "SudoSecurePass@123"
    autoDeploy: yes
    numInstances: 1
    resources:
      cpu: 2
      memory: 4GB
      disk: 10GB
