services:
  - type: web
    name: code-server-render
    env: docker
    plan: standard
    region: frankfurt
    dockerfilePath: Dockerfile
    healthCheckPath: /
    envVars:
      - key: CODE_SERVER_PASSWORD
        value: "SecurePass@123"
      - key: PASSWORD
        value: "SecurePass@123"
      - key: USERNAME
        value: developer
      - key: PUID
        value: "1001"
      - key: PGID
        value: "1001"
    autoDeploy: true
